export interface ProductWithDetails {
    product: ProductResponse;        // The product details
    artisan: Artisan;        // The artisan who created the product
    reviews: Review[];       // Array of reviews for the product
    relatedProducts: ProductResponse[]; // Array of related products
}


export interface ProductFormValues {
    title: string;
    description: string;
    createdBy: string;
    category: string;
    price: string;
    slug?: string;
    materials: string[];
    productImage: File[] | string[];
}




export interface Product {
    title: string;
    description: string;
    materials: string[];       // array of strings
    createdBy: string;         // artisan or designer username
    category: string;
    price: number;
    images: File[] | string[]; // array of File objects (for upload) or strings (URLs from backend)
}

export interface ProductResponse {
    title: string;
    description: string;
    materials: string[];       // array of strings
    createdBy: string;         // artisan or designer username
    category: string;
    price: number;
    images: string[]; // array of File objects (for upload) or strings (URLs from backend)
    slug: string;
    _id: string;           // optional, generated on backend
    rating: number;
}




export interface Artisan {
    _id: string;                  // MongoDB Object ID for Artisan
    fullName: string;              // Full name of the artisan
    description: string;          // Artisan's description
    profilePic: string;           // URL to the artisan's profile picture
    slug: string;                 // Artisan's slug (unique identifier)
    createdAt: string;            // Timestamp of when the artisan was created
    updatedAt: string;            // Timestamp of when the artisan was last updated
    __v: number;                  // Version key (auto-generated by MongoDB)
}

export interface Review {
    _id: string;                  // MongoDB Object ID for the review
    productId: string;            // The ID of the product this review is related to
    user: string;
    rating: number;               // Rating given in the review
    comment: string;              // Text of the review comment
    createdAt: string;            // Timestamp of when the review was created
    updatedAt: string;
}


export interface RelatedProduct {
    relatedProducts: Product[];
}